export const SERIES_DATA = [
  { id: 1, name: "AEROX ALPHA Series" },
  { id: 2, name: "Aerox Series" },
  { id: 3, name: "ALL New NMAX Series" },
  { id: 4, name: "R15 Series" },
  { id: 5, name: "X-RIDE Series" },
  { id: 6, name: "ALL NEW XSR 155" },
  { id: 7, name: "FAZZIO SERIES" },
  { id: 8, name: "Free GO Series" },
  { id: 9, name: "GEAR Series" },
  { id: 10, name: "GEAR Ultima Series" },
  { id: 11, name: "FILANO SERIES" },
  { id: 12, name: "Jupiter Series" },
  { id: 13, name: "MX King Series" },
  { id: 14, name: "MIO Series" },
  { id: 15, name: "NMAX NEO Series" },
  { id: 16, name: "NMAX TURBO Series" },
  { id: 17, name: "WR 155 R" },
  { id: 18, name: "XMAX" },
  { id: 19, name: "Vega Series" },
  { id: 20, name: "Lexi Series" },
  { id: 21, name: "VIXION Series" },
];

export const BRANCHES_DATA = [
  { name: "Yamaha APT Pranoto", code: "SMA-YMH-APT" },
  { name: "Yamaha A. Yani", code: "SMA-YMH-AYN" },
  { name: "Yamaha Petung", code: "SMA-YMH-PTG" },
  { name: "Yamaha Tanah Grogot", code: "SMA-YMH-TGT" },
  { name: "Yamaha Pasar Loajanan", code: "SMA-YMH-LOA" },
  { name: "Yamaha Lambung Mangkurat", code: "SMA-YMH-LBM" },
  { name: "Yamaha Tenggarong", code: "SMA-YMH-TGR" },
  { name: "Yamaha Melak", code: "SMA-YMH-MLK" },
  { name: "Yamaha Barong Tongkok", code: "SMA-YMH-BAR" },
  { name: "Yamaha Bontang", code: "SMA-YMH-BTG" },
  { name: "Yamaha Sangatta", code: "SMA-YMH-SGT" },
];

export const TYPES_DATA = [
  {
    code: "D09200",
    descriptionUnit: "AEROX ALPHA",
    type: "AEROX ALPHA",
    seriesId: 1,
  },
  {
    code: "D09100",
    descriptionUnit: "AEROX ALPHA CYBERCITY",
    type: "AEROX ALPHA CYBERCITY",
    seriesId: 1,
  },
  {
    code: "BWP100",
    descriptionUnit: "AEROX ALPHA TURBO",
    type: "AEROX ALPHA TURBO",
    seriesId: 1,
  },
  {
    code: "BWP200",
    descriptionUnit: "AEROX ALPHA TURBO ULTIMATE",
    type: "AEROX ALPHA TURBO ULTIMATE",
    seriesId: 1,
  },
  {
    code: "BBPF00",
    descriptionUnit: "AEROX 155",
    type: "ALL NEW AEROX 155",
    seriesId: 2,
  },
  {
    code: "BBP200 M/T",
    descriptionUnit: "ALL NEW AEROX 155 C ABS",
    type: "ALL NEW AEROX 155 C ABS",
    seriesId: 2,
  },
  {
    code: "BBPG00",
    descriptionUnit: "AEROX 155 CYBERCITY",
    type: "ALL NEW AEROX 155 CYBERCITY",
    seriesId: 2,
  },
  {
    code: "B6Y1 M/T",
    descriptionUnit: "ALL NEW NMAX 155 ABS",
    type: "ALL NEW NMAX 155 ABS",
    seriesId: 3,
  },
  {
    code: "B6HT00/B6HU00",
    descriptionUnit: "ALL NEW NMAX 155 S",
    type: "ALL NEW NMAX 155 S",
    seriesId: 3,
  },
  {
    code: "BDJ200",
    descriptionUnit: "ALL NEW R15 CONNECTED",
    type: "ALL NEW R15 CONNECTED",
    seriesId: 4,
  },
  {
    code: "BY83 A/T",
    descriptionUnit: "ALL NEW X - RIDE 125 ABS",
    type: "ALL NEW XRIDE 125 ABS",
    seriesId: 5,
  },
  {
    code: "BBS1 M/T (NK)",
    descriptionUnit: "ALL NEW XSR 155 R",
    type: "ALL NEW XSR 155",
    seriesId: 6,
  },
  {
    code: "BEJ300 A/T",
    descriptionUnit: "FAZZIO CONNECTED LUX",
    type: "FAZZIO CONNECTED LUX",
    seriesId: 7,
  },
  {
    code: "BEJB00",
    descriptionUnit: "FAZZIO HYBRID",
    type: "FAZZIO HYBRID",
    seriesId: 7,
  },
  {
    code: "BEJA00",
    descriptionUnit: "FAZZIO HYBRID LUX",
    type: "FAZZIO HYBRID LUX",
    seriesId: 7,
  },
  {
    code: "BEJ400 A/T",
    descriptionUnit: "FAZZIO NEO HYBRID / HYBRID NEO",
    type: "FAZZIO NEO HYBRID",
    seriesId: 7,
  },
  {
    code: "BKU100",
    descriptionUnit: "FREE GO 125",
    type: "Free GO 125",
    seriesId: 8,
  },
  {
    code: "BKU200",
    descriptionUnit: "FREE GO 125 C",
    type: "FREEGO 125 CONNECTED",
    seriesId: 8,
  },
  {
    code: "B3W100 A/T",
    descriptionUnit: "GEAR 125",
    type: "GEAR 125",
    seriesId: 9,
  },
  {
    code: "B3W200 A/T",
    descriptionUnit: "GEAR 125 S",
    type: "GEAR 125 S VERSION",
    seriesId: 9,
  },
  {
    code: "BXY100",
    descriptionUnit: "G ULTIMA HYBRID",
    type: "GEAR ULTIMA HYBRID",
    seriesId: 10,
  },
  {
    code: "BJM100 A/T",
    descriptionUnit: "GRAND FILANO LUX",
    type: "GRAND FILANO LUX",
    seriesId: 11,
  },
  {
    code: "BJM400 A/T",
    descriptionUnit: "GRAND FILANO NEO HYBRID",
    type: "GRAND FILANO NEO HYBRID",
    seriesId: 11,
  },
  {
    code: "UE11",
    descriptionUnit: "JUPITER Z FI CW / FURIOUS",
    type: "JUPITER Z CW FI",
    seriesId: 12,
  },
  {
    code: "2PV1-M",
    descriptionUnit: "MX KING",
    type: "MX KING 150",
    seriesId: 13,
  },
  {
    code: "2PVL00",
    descriptionUnit: "MX KING CYBERCITY",
    type: "MX KING 150 CYBERCITY",
    seriesId: 13,
  },
  {
    code: "2PH1 A/T",
    descriptionUnit: "MIO M3 125 BLUE CORE CW",
    type: "NEW MIO M3 CW 125",
    seriesId: 14,
  },
  {
    code: "BPA100",
    descriptionUnit: "NMAX NEO",
    type: "NMAX NEO",
    seriesId: 15,
  },
  {
    code: "BTE100",
    descriptionUnit: "NMAX NEO S",
    type: "NMAX NEO S",
    seriesId: 15,
  },
  {
    code: "BTD100",
    descriptionUnit: "NMAX TURBO",
    type: "NMAX TURBO",
    seriesId: 16,
  },
  {
    code: "BLS100",
    descriptionUnit: "NMAX TURBO TECH MAX",
    type: "NMAX TURBO TECH MAX",
    seriesId: 16,
  },
  {
    code: "BLS200",
    descriptionUnit: "NMAX TURBO TECH MAX ULTIMATE",
    type: "NMAX TURBO TECH MAX ULTIMATE",
    seriesId: 16,
  },
  {
    code: "B3M1 M/T",
    descriptionUnit: "WR 155 R",
    type: "WR 155 R",
    seriesId: 17,
  },
  {
    code: "BPV100",
    descriptionUnit: "X-MAX C",
    type: "XMAX CONNECTED",
    seriesId: 18,
  },
  {
    code: "MH3SG",
    descriptionUnit: "X-MAX TECH MAX",
    type: "XMAX TECH MAX",
    seriesId: 18,
  },
  {
    code: "1-FD",
    descriptionUnit: "FORCE ELEGAN DB CW",
    type: "FORCE ELEGAN DB CW",
    seriesId: 19,
  },
  {
    code: "B6HC00 M/T",
    descriptionUnit: "ALL NEW NMAX 155 C",
    type: "ALL NEW NMAX 155 C",
    seriesId: 3,
  },
  {
    code: "B6HB M/T",
    descriptionUnit: "ALL NEW NMAX 155",
    type: "ALL NEW NMAX 155",
    seriesId: 3,
  },
  {
    code: "BDJ300 - S",
    descriptionUnit: "ALL NEW R15M CONNECTED ABS WGP 60 th",
    type: "ALL NEW R15M CONNECTED ABS WGP 60 th",
    seriesId: 4,
  },
  {
    code: "BEJ100 A/T",
    descriptionUnit: "FAZZIO CONNECTED NEO",
    type: "FAZZIO CONNECTED NEO",
    seriesId: 7,
  },
  {
    code: "BPN300",
    descriptionUnit: "LEXI LX 155 S CONNECTED",
    type: "LEXI LX 155 S CONNECTED",
    seriesId: 20,
  },
  {
    code: "BPN100",
    descriptionUnit: "LEXI LX 155 CONNECTED ABS",
    type: "LEXI LX 155 CONNECTED ABS",
    seriesId: 20,
  },
  {
    code: "BPN200",
    descriptionUnit: "LEXI LX 155 CONNECTED",
    type: "LEXI LX 155 CONNECTED",
    seriesId: 20,
  },
  {
    code: "BXY200",
    descriptionUnit: "G ULTIMA HYBRID S",
    type: "GEAR ULTIMA HYBRID S",
    seriesId: 10,
  },
  {
    code: "BK81 - S",
    descriptionUnit: "ALL NEW VIXION",
    type: "ALL NEW VIXION",
    seriesId: 21,
  },
  {
    code: "BPN900",
    descriptionUnit: "LEXI LX 155",
    type: "LEXI LX 155",
    seriesId: 20,
  },
  {
    code: "BPN800",
    descriptionUnit: "LEXI LX 155 S",
    type: "LEXI LX 155 S",
    seriesId: 20,
  },
  {
    code: "BT31 - S (G3S7)",
    descriptionUnit: "ALL NEW VIXION - R",
    type: "ALL NEW VIXION - R",
    seriesId: 21,
  },
  {
    code: "B3W700-010",
    descriptionUnit: "GEAR 125 - SE",
    type: "GEAR 125 SPESIAL EDITION",
    seriesId: 9,
  },
  {
    code: "B3W600",
    descriptionUnit: "GEAR 125 S - SE",
    type: "GEAR 125 S SPESIAL EDITION",
    seriesId: 9,
  },
];
